export const Countries = [
    {"en_name": "Egypt", "ar_name": "مصر", "code": "EG"},
    {"en_name": "Saudi Arabia", "ar_name": "السعودية", "code": "SA"},
    {"en_name": "Oman", "ar_name": "عمان", "code": "OM"},
    {"en_name": "Jordan", "ar_name": "الأردن", "code": "JO"},
    {"en_name": "Kuwait", "ar_name": "الكويت", "code": "KW"},
    {"en_name": "Libya", "ar_name": "ليبيا", "code": "LY"},
    {"en_name": "United Arab Emirates", "ar_name": "الإمارات", "code": "AE"},
    {"en_name": "United Kingdom", "ar_name": "المملكة المتحدة", "code": "GB"},
    {"en_name": "United States", "ar_name": "الولايات المتحدة", "code": "US"},
    {"en_name": "France", "ar_name": "فرنسا", "code": "FR"},
    {"en_name": "Lebanon", "ar_name": "لبنان", "code": "LB"},
    {"en_name": "Qatar", "ar_name": "قطر", "code": "QA"},
    {"en_name": "Bahrain", "ar_name": "البحرين", "code": "BH"},
    {"en_name": "Algeria", "ar_name": "الجزائر", "code": "DZ"},
    {"en_name": "Morocco", "ar_name": "المغرب", "code": "MA"},
    {"en_name": "Sudan", "ar_name": "السودان", "code": "SD"},
    {"en_name": "South Sudan", "ar_name": "جنوب السودان", "code": "SS"},
    {"en_name": "Tunisia", "ar_name": "تونس", "code": "TN"},
    {"en_name": "Turkey", "ar_name": "تركيا", "code": "TR"},
    {"en_name": "China", "ar_name": "الصين", "code": "CN"},
    {"en_name": "Japan", "ar_name": "اليابان", "code": "JP"},
    {"en_name": "Palestine", "ar_name": "فلسطين", "code": "PS"},
    {"en_name": "North Korea", "ar_name": "كوريا الشمالية", "code": "KP"},
    {"en_name": "South Korea", "ar_name": "كوريا الجنوبية", "code": "KR"},
    {"en_name": "Greece", "ar_name": "اليونان", "code": "GR"},
    {"en_name": "Afghanistan", "ar_name": "أفغانستان", "code": "AF"},
    {"en_name": "Albania", "ar_name": "ألبانيا", "code": "AL"},
    {"en_name": "Andorra", "ar_name": "أندورا", "code": "AD"},
    {"en_name": "Angola", "ar_name": "أنغولا", "code": "AO"},
    {"en_name": "Antigua and Barbuda", "ar_name": "أنتيغوا وبربودا", "code": "AG"},
    {"en_name": "Argentina", "ar_name": "الأرجنتين", "code": "AR"},
    {"en_name": "Armenia", "ar_name": "أرمينيا", "code": "AM"},
    {"en_name": "Australia", "ar_name": "أستراليا", "code": "AU"},
    {"en_name": "Austria", "ar_name": "النمسا", "code": "AT"},
    {"en_name": "Azerbaijan", "ar_name": "أذربيجان", "code": "AZ"},
    {"en_name": "Bahamas", "ar_name": "جزر البهاما", "code": "BS"},
    {"en_name": "Bangladesh", "ar_name": "بنغلاديش", "code": "BD"},
    {"en_name": "Barbados", "ar_name": "بربادوس", "code": "BB"},
    {"en_name": "Belarus", "ar_name": "بيلاروسيا", "code": "BY"},
    {"en_name": "Belgium", "ar_name": "بلجيكا", "code": "BE"},
    {"en_name": "Belize", "ar_name": "بليز", "code": "BZ"},
    {"en_name": "Benin", "ar_name": "بنين", "code": "BJ"},
    {"en_name": "Bhutan", "ar_name": "بوتان", "code": "BT"},
    {"en_name": "Bolivia", "ar_name": "بوليفيا", "code": "BO"},
    {"en_name": "Bosnia and Herzegovina", "ar_name": "البوسنة والهرسك", "code": "BA"},
    {"en_name": "Botswana", "ar_name": "بوتسوانا", "code": "BW"},
    {"en_name": "Brazil", "ar_name": "البرازيل", "code": "BR"},
    {"en_name": "Brunei", "ar_name": "بروناي", "code": "BN"},
    {"en_name": "Bulgaria", "ar_name": "بلغاريا", "code": "BG"},
    {"en_name": "Burkina Faso", "ar_name": "بوركينا فاسو", "code": "BF"},
    {"en_name": "Burundi", "ar_name": "بوروندي", "code": "BI"},
    {"en_name": "Cabo Verde", "ar_name": "الرأس الأخضر", "code": "CV"},
    {"en_name": "Cambodia", "ar_name": "كمبوديا", "code": "KH"},
    {"en_name": "Cameroon", "ar_name": "الكاميرون", "code": "CM"},
    {"en_name": "Canada", "ar_name": "كندا", "code": "CA"},
    {"en_name": "Central African Republic", "ar_name": "جمهورية أفريقيا الوسطى", "code": "CF"},
    {"en_name": "Chad", "ar_name": "تشاد", "code": "TD"},
    {"en_name": "Chile", "ar_name": "تشيلي", "code": "CL"},
    {"en_name": "Colombia", "ar_name": "كولومبيا", "code": "CO"},
    {"en_name": "Comoros", "ar_name": "جزر القمر", "code": "KM"},
    {"en_name": "Congo, Democratic Republic of the", "ar_name": "جمهورية الكونغو الديمقراطية", "code": "CD"},
    {"en_name": "Congo, Republic of the", "ar_name": "جمهورية الكونغو", "code": "CG"},
    {"en_name": "Costa Rica", "ar_name": "كوستاريكا", "code": "CR"},
    {"en_name": "Croatia", "ar_name": "كرواتيا", "code": "HR"},
    {"en_name": "Cuba", "ar_name": "كوبا", "code": "CU"},
    {"en_name": "Cyprus", "ar_name": "قبرص", "code": "CY"},
    {"en_name": "Czech Republic", "ar_name": "جمهورية التشيك", "code": "CZ"},
    {"en_name": "Denmark", "ar_name": "الدنمارك", "code": "DK"},
    {"en_name": "Djibouti", "ar_name": "جيبوتي", "code": "DJ"},
    {"en_name": "Dominica", "ar_name": "دومينيكا", "code": "DM"},
    {"en_name": "Dominican Republic", "ar_name": "جمهورية الدومينيكان", "code": "DO"},
    {"en_name": "Ecuador", "ar_name": "الإكوادور", "code": "EC"},
    {"en_name": "El Salvador", "ar_name": "السلفادور", "code": "SV"},
    {"en_name": "Equatorial Guinea", "ar_name": "غينيا الاستوائية", "code": "GQ"},
    {"en_name": "Eritrea", "ar_name": "إريتريا", "code": "ER"},
    {"en_name": "Estonia", "ar_name": "إستونيا", "code": "EE"},
    {"en_name": "Eswatini", "ar_name": "إسواتيني", "code": "SZ"},
    {"en_name": "Ethiopia", "ar_name": "إثيوبيا", "code": "ET"},
    {"en_name": "Fiji", "ar_name": "فيجي", "code": "FJ"},
    {"en_name": "Finland", "ar_name": "فنلندا", "code": "FI"},
    {"en_name": "Gabon", "ar_name": "الغابون", "code": "GA"},
    {"en_name": "Gambia", "ar_name": "غامبيا", "code": "GM"},
    {"en_name": "Georgia", "ar_name": "جورجيا", "code": "GE"},
    {"en_name": "Germany", "ar_name": "ألمانيا", "code": "DE"},
    {"en_name": "Ghana", "ar_name": "غانا", "code": "GH"},
    {"en_name": "Grenada", "ar_name": "غرينادا", "code": "GD"},
    {"en_name": "Guatemala", "ar_name": "غواتيمالا", "code": "GT"},
    {"en_name": "Guinea", "ar_name": "غينيا", "code": "GN"},
    {"en_name": "Guinea-Bissau", "ar_name": "غينيا بيساو", "code": "GW"},
    {"en_name": "Guyana", "ar_name": "غيانا", "code": "GY"},
    {"en_name": "Haiti", "ar_name": "هايتي", "code": "HT"},
    {"en_name": "Honduras", "ar_name": "هندوراس", "code": "HN"},
    {"en_name": "Hungary", "ar_name": "المجر", "code": "HU"},
    {"en_name": "Iceland", "ar_name": "آيسلندا", "code": "IS"},
    {"en_name": "India", "ar_name": "الهند", "code": "IN"},
    {"en_name": "Indonesia", "ar_name": "إندونيسيا", "code": "ID"},
    {"en_name": "Iran", "ar_name": "إيران", "code": "IR"},
    {"en_name": "Iraq", "ar_name": "العراق", "code": "IQ"},
    {"en_name": "Ireland", "ar_name": "أيرلندا", "code": "IE"},
    {"en_name": "Israel", "ar_name": "إسرائيل", "code": "IL"},
    {"en_name": "Italy", "ar_name": "إيطاليا", "code": "IT"},
    {"en_name": "Jamaica", "ar_name": "جامايكا", "code": "JM"},
    {"en_name": "Kazakhstan", "ar_name": "كازاخستان", "code": "KZ"},
    {"en_name": "Kenya", "ar_name": "كينيا", "code": "KE"},
    {"en_name": "Kiribati", "ar_name": "كيريباتي", "code": "KI"},
    {"en_name": "Kyrgyzstan", "ar_name": "قيرغيزستان", "code": "KG"},
    {"en_name": "Laos", "ar_name": "لاوس", "code": "LA"},
    {"en_name": "Latvia", "ar_name": "لاتفيا", "code": "LV"},
    {"en_name": "Lesotho", "ar_name": "ليسوتو", "code": "LS"},
    {"en_name": "Liberia", "ar_name": "ليبيريا", "code": "LR"},
    {"en_name": "Liechtenstein", "ar_name": "ليختنشتاين", "code": "LI"},
    {"en_name": "Lithuania", "ar_name": "ليتوانيا", "code": "LT"},
    {"en_name": "Luxembourg", "ar_name": "لوكسمبورغ", "code": "LU"},
    {"en_name": "Madagascar", "ar_name": "مدغشقر", "code": "MG"},
    {"en_name": "Malawi", "ar_name": "مالاوي", "code": "MW"},
    {"en_name": "Malaysia", "ar_name": "ماليزيا", "code": "MY"},
    {"en_name": "Maldives", "ar_name": "جزر المالديف", "code": "MV"},
    {"en_name": "Mali", "ar_name": "مالي", "code": "ML"},
    {"en_name": "Malta", "ar_name": "مالطا", "code": "MT"},
    {"en_name": "Marshall Islands", "ar_name": "جزر مارشال", "code": "MH"},
    {"en_name": "Mauritania", "ar_name": "موريتانيا", "code": "MR"},
    {"en_name": "Mauritius", "ar_name": "موريشيوس", "code": "MU"},
    {"en_name": "Mexico", "ar_name": "المكسيك", "code": "MX"},
    {"en_name": "Micronesia", "ar_name": "ميكرونيزيا", "code": "FM"},
    {"en_name": "Moldova", "ar_name": "مولدوفا", "code": "MD"},
    {"en_name": "Monaco", "ar_name": "موناكو", "code": "MC"},
    {"en_name": "Mongolia", "ar_name": "منغوليا", "code": "MN"},
    {"en_name": "Montenegro", "ar_name": "الجبل الأسود", "code": "ME"},
    {"en_name": "Mozambique", "ar_name": "موزمبيق", "code": "MZ"},
    {"en_name": "Myanmar", "ar_name": "ميانمار", "code": "MM"},
    {"en_name": "Namibia", "ar_name": "ناميبيا", "code": "NA"},
    {"en_name": "Nauru", "ar_name": "ناورو", "code": "NR"},
    {"en_name": "Nepal", "ar_name": "نيبال", "code": "NP"},
    {"en_name": "Netherlands", "ar_name": "هولندا", "code": "NL"},
    {"en_name": "New Zealand", "ar_name": "نيوزيلندا", "code": "NZ"},
    {"en_name": "Nicaragua", "ar_name": "نيكاراغوا", "code": "NI"},
    {"en_name": "Niger", "ar_name": "النيجر", "code": "NE"},
    {"en_name": "Nigeria", "ar_name": "نيجيريا", "code": "NG"},
    {"en_name": "North Macedonia", "ar_name": "مقدونيا الشمالية", "code": "MK"},
    {"en_name": "Norway", "ar_name": "النرويج", "code": "NO"},
    {"en_name": "Pakistan", "ar_name": "باكستان", "code": "PK"},
    {"en_name": "Palau", "ar_name": "بالاو", "code": "PW"},
    {"en_name": "Panama", "ar_name": "بنما", "code": "PA"},
    {"en_name": "Papua New Guinea", "ar_name": "بابوا غينيا الجديدة", "code": "PG"},
    {"en_name": "Paraguay", "ar_name": "باراغواي", "code": "PY"},
    {"en_name": "Peru", "ar_name": "بيرو", "code": "PE"},
    {"en_name": "Philippines", "ar_name": "الفلبين", "code": "PH"},
    {"en_name": "Poland", "ar_name": "بولندا", "code": "PL"},
    {"en_name": "Portugal", "ar_name": "البرتغال", "code": "PT"},
    {"en_name": "Romania", "ar_name": "رومانيا", "code": "RO"},
    {"en_name": "Russia", "ar_name": "روسيا", "code": "RU"},
    {"en_name": "Rwanda", "ar_name": "رواندا", "code": "RW"},
    {"en_name": "Saint Kitts and Nevis", "ar_name": "سانت كيتس ونيفيس", "code": "KN"},
    {"en_name": "Saint Lucia", "ar_name": "سانت لوسيا", "code": "LC"},
    {"en_name": "Saint Vincent and the Grenadines", "ar_name": "سانت فنسنت والغرينادين", "code": "VC"},
    {"en_name": "Samoa", "ar_name": "ساموا", "code": "WS"},
    {"en_name": "San Marino", "ar_name": "سان مارينو", "code": "SM"},
    {"en_name": "Sao Tome and Principe", "ar_name": "ساو تومي وبرينسيب", "code": "ST"},
    {"en_name": "Senegal", "ar_name": "السنغال", "code": "SN"},
    {"en_name": "Serbia", "ar_name": "صربيا", "code": "RS"},
    {"en_name": "Seychelles", "ar_name": "سيشيل", "code": "SC"},
    {"en_name": "Sierra Leone", "ar_name": "سيراليون", "code": "SL"},
    {"en_name": "Singapore", "ar_name": "سنغافورة", "code": "SG"},
    {"en_name": "Slovakia", "ar_name": "سلوفاكيا", "code": "SK"},
    {"en_name": "Slovenia", "ar_name": "سلوفينيا", "code": "SI"},
    {"en_name": "Solomon Islands", "ar_name": "جزر سليمان", "code": "SB"},
    {"en_name": "Somalia", "ar_name": "الصومال", "code": "SO"},
    {"en_name": "South Africa", "ar_name": "جنوب أفريقيا", "code": "ZA"},
    {"en_name": "Spain", "ar_name": "إسبانيا", "code": "ES"},
    {"en_name": "Sri Lanka", "ar_name": "سريلانكا", "code": "LK"},
    {"en_name": "Suriname", "ar_name": "سورينام", "code": "SR"},
    {"en_name": "Sweden", "ar_name": "السويد", "code": "SE"},
    {"en_name": "Switzerland", "ar_name": "سويسرا", "code": "CH"},
    {"en_name": "Syria", "ar_name": "سوريا", "code": "SY"},
    {"en_name": "Tajikistan", "ar_name": "طاجيكستان", "code": "TJ"},
    {"en_name": "Tanzania", "ar_name": "تنزانيا", "code": "TZ"},
    {"en_name": "Thailand", "ar_name": "تايلاند", "code": "TH"},
    {"en_name": "Timor-Leste", "ar_name": "تيمور الشرقية", "code": "TL"},
    {"en_name": "Togo", "ar_name": "توغو", "code": "TG"},
    {"en_name": "Tonga", "ar_name": "تونغا", "code": "TO"},
    {"en_name": "Trinidad and Tobago", "ar_name": "ترينيداد وتوباغو", "code": "TT"},
    {"en_name": "Turkmenistan", "ar_name": "تركمانستان", "code": "TM"},
    {"en_name": "Tuvalu", "ar_name": "توفالو", "code": "TV"},
    {"en_name": "Uganda", "ar_name": "أوغندا", "code": "UG"},
    {"en_name": "Ukraine", "ar_name": "أوكرانيا", "code": "UA"},
    {"en_name": "Uruguay", "ar_name": "أوروغواي", "code": "UY"},
    {"en_name": "Uzbekistan", "ar_name": "أوزبكستان", "code": "UZ"},
    {"en_name": "Vanuatu", "ar_name": "فانواتو", "code": "VU"},
    {"en_name": "Vatican City", "ar_name": "الفاتيكان", "code": "VA"},
    {"en_name": "Venezuela", "ar_name": "فنزويلا", "code": "VE"},
    {"en_name": "Vietnam", "ar_name": "فيتنام", "code": "VN"},
    {"en_name": "Yemen", "ar_name": "اليمن", "code": "YE"},
    {"en_name": "Zambia", "ar_name": "زامبيا", "code": "ZM"},
    {"en_name": "Zimbabwe", "ar_name": "زيمبابوي", "code": "ZW"}
]
