export const Keys = [
    {"code": "+20", "en_name": "Egypt", "ar_name": "مصر"},
    {"code": "+966", "en_name": "Saudi Arabia", "ar_name": "المملكة السعودية"},
    {"code": "+1", "en_name": "United States", "ar_name": "الولايات المتحدة"},
    {"code": "+965", "en_name": "Kuwait", "ar_name": "الكويت"},
    {"code": "+973", "en_name": "Bahrain", "ar_name": "البحرين"},
    {"code": "+962", "en_name": "Jordan", "ar_name": "الأردن"},
    {"code": "+974", "en_name": "Qatar", "ar_name": "قطر"},
    {"code": "+971", "en_name": "Emirates", "ar_name": "الإمارات"},
    {"code": "+961", "en_name": "Lebanon", "ar_name": "لبنان"},
    {"code": "+963", "en_name": "Syria", "ar_name": "سوريا"},
    {"code": "+964", "en_name": "Iraq", "ar_name": "العراق"},
    {"code": "+967", "en_name": "Yemen", "ar_name": "اليمن"},
    {"code": "+968", "en_name": "Oman", "ar_name": "عمان"},
    {"code": "+970", "en_name": "Palestine", "ar_name": "فلسطين"},
    {"code": "+960", "en_name": "Maldives", "ar_name": "المالديف"},
    {"code": "+98", "en_name": "Iran", "ar_name": "إيران"},
    {"code": "+212", "en_name": "Morocco", "ar_name": "المغرب"},
    {"code": "+213", "en_name": "Algeria", "ar_name": "الجزائر"},
    {"code": "+216", "en_name": "Tunisia", "ar_name": "تونس"},
    {"code": "+218", "en_name": "Libya", "ar_name": "ليبيا"},
    {"code": "+7", "en_name": "Russia", "ar_name": "روسيا"},
    {"code": "+27", "en_name": "South Africa", "ar_name": "جنوب أفريقيا"},
    {"code": "+30", "en_name": "Greece", "ar_name": "اليونان"},
    {"code": "+31", "en_name": "Netherlands", "ar_name": "هولندا"},
    {"code": "+32", "en_name": "Belgium", "ar_name": "بلجيكا"},
    {"code": "+33", "en_name": "France", "ar_name": "فرنسا"},
    {"code": "+34", "en_name": "Spain", "ar_name": "إسبانيا"},
    {"code": "+36", "en_name": "Hungary", "ar_name": "المجر"},
    {"code": "+39", "en_name": "Italy", "ar_name": "إيطاليا"},
    {"code": "+40", "en_name": "Romania", "ar_name": "رومانيا"},
    {"code": "+41", "en_name": "Switzerland", "ar_name": "سويسرا"},
    {"code": "+43", "en_name": "Austria", "ar_name": "النمسا"},
    {"code": "+44", "en_name": "United Kingdom", "ar_name": "المملكة المتحدة"},
    {"code": "+45", "en_name": "Denmark", "ar_name": "الدنمارك"},
    {"code": "+46", "en_name": "Sweden", "ar_name": "السويد"},
    {"code": "+47", "en_name": "Norway", "ar_name": "النرويج"},
    {"code": "+48", "en_name": "Poland", "ar_name": "بولندا"},
    {"code": "+49", "en_name": "Germany", "ar_name": "ألمانيا"},
    {"code": "+51", "en_name": "Peru", "ar_name": "بيرو"},
    {"code": "+52", "en_name": "Mexico", "ar_name": "المكسيك"},
    {"code": "+53", "en_name": "Cuba", "ar_name": "كوبا"},
    {"code": "+54", "en_name": "Argentina", "ar_name": "الأرجنتين"},
    {"code": "+55", "en_name": "Brazil", "ar_name": "البرازيل"},
    {"code": "+56", "en_name": "Chile", "ar_name": "شيلي"},
    {"code": "+57", "en_name": "Colombia", "ar_name": "كولومبيا"},
    {"code": "+58", "en_name": "Venezuela", "ar_name": "فنزويلا"},
    {"code": "+60", "en_name": "Malaysia", "ar_name": "ماليزيا"},
    {"code": "+61", "en_name": "Australia", "ar_name": "أستراليا"},
    {"code": "+62", "en_name": "Indonesia", "ar_name": "إندونيسيا"},
    {"code": "+63", "en_name": "Philippines", "ar_name": "الفلبين"},
    {"code": "+64", "en_name": "New Zealand", "ar_name": "نيوزيلندا"},
    {"code": "+65", "en_name": "Singapore", "ar_name": "سنغافورة"},
    {"code": "+66", "en_name": "Thailand", "ar_name": "تايلاند"},
    {"code": "+81", "en_name": "Japan", "ar_name": "اليابان"},
    {"code": "+82", "en_name": "South Korea", "ar_name": "كوريا الجنوبية"},
    {"code": "+84", "en_name": "Vietnam", "ar_name": "فيتنام"},
    {"code": "+86", "en_name": "China", "ar_name": "الصين"},
    {"code": "+90", "en_name": "Turkey", "ar_name": "تركيا"},
    {"code": "+91", "en_name": "India", "ar_name": "الهند"},
    {"code": "+92", "en_name": "Pakistan", "ar_name": "باكستان"},
    {"code": "+93", "en_name": "Afghanistan", "ar_name": "أفغانستان"},
    {"code": "+94", "en_name": "Sri Lanka", "ar_name": "سريلانكا"},
    {"code": "+95", "en_name": "Myanmar", "ar_name": "ميانمار"},
    {"code": "+220", "en_name": "Gambia", "ar_name": "غامبيا"},
    {"code": "+221", "en_name": "Senegal", "ar_name": "السنغال"},
    {"code": "+222", "en_name": "Mauritania", "ar_name": "موريتانيا"},
    {"code": "+223", "en_name": "Mali", "ar_name": "مالي"},
    {"code": "+224", "en_name": "Guinea", "ar_name": "غينيا"},
    {"code": "+225", "en_name": "Ivory Coast", "ar_name": "ساحل العاج"},
    {"code": "+226", "en_name": "Burkina Faso", "ar_name": "بوركينا فاسو"},
    {"code": "+227", "en_name": "Niger", "ar_name": "النيجر"},
    {"code": "+228", "en_name": "Togo", "ar_name": "توغو"},
    {"code": "+229", "en_name": "Benin", "ar_name": "بنين"},
    {"code": "+230", "en_name": "Mauritius", "ar_name": "موريشيوس"},
    {"code": "+231", "en_name": "Liberia", "ar_name": "ليبيريا"},
    {"code": "+232", "en_name": "Sierra Leone", "ar_name": "سيراليون"},
    {"code": "+233", "en_name": "Ghana", "ar_name": "غانا"},
    {"code": "+234", "en_name": "Nigeria", "ar_name": "نيجيريا"},
    {"code": "+235", "en_name": "Chad", "ar_name": "تشاد"},
    {"code": "+236", "en_name": "African Republic", "ar_name": "جمهورية أفريقيا"},
    {"code": "+237", "en_name": "Cameroon", "ar_name": "الكاميرون"},
    {"code": "+238", "en_name": "Cape Verde", "ar_name": "الرأس الأخضر"},
    {"code": "+239", "en_name": "São Tomé", "ar_name": "ساو تومي"},
    {"code": "+240", "en_name": "Equatorial Guinea", "ar_name": "غينيا الاستوائية"},
    {"code": "+241", "en_name": "Gabon", "ar_name": "الغابون"},
    {"code": "+242", "en_name": "Congo", "ar_name": "الكونغو"},
    {"code": "+244", "en_name": "Angola", "ar_name": "أنغولا"},
    {"code": "+245", "en_name": "Guinea-Bissau", "ar_name": "غينيا بيساو"},
    {"code": "+247", "en_name": "Ascension Island", "ar_name": "جزيرة أسينشين"},
    {"code": "+248", "en_name": "Seychelles", "ar_name": "سيشل"},
    {"code": "+249", "en_name": "Sudan", "ar_name": "السودان"},
    {"code": "+250", "en_name": "Rwanda", "ar_name": "رواندا"},
    {"code": "+251", "en_name": "Ethiopia", "ar_name": "إثيوبيا"},
    {"code": "+252", "en_name": "Somalia", "ar_name": "الصومال"},
    {"code": "+253", "en_name": "Djibouti", "ar_name": "جيبوتي"},
    {"code": "+254", "en_name": "Kenya", "ar_name": "كينيا"},
    {"code": "+255", "en_name": "Tanzania", "ar_name": "تنزانيا"},
    {"code": "+256", "en_name": "Uganda", "ar_name": "أوغندا"},
    {"code": "+257", "en_name": "Burundi", "ar_name": "بوروندي"},
    {"code": "+258", "en_name": "Mozambique", "ar_name": "موزمبيق"},
    {"code": "+260", "en_name": "Zambia", "ar_name": "زامبيا"},
    {"code": "+261", "en_name": "Madagascar", "ar_name": "مدغشقر"},
    {"code": "+262", "en_name": "Réunion", "ar_name": "رينيون"},
    {"code": "+263", "en_name": "Zimbabwe", "ar_name": "زيمبابوي"},
    {"code": "+264", "en_name": "Namibia", "ar_name": "ناميبيا"},
    {"code": "+265", "en_name": "Malawi", "ar_name": "مالاوي"},
    {"code": "+266", "en_name": "Lesotho", "ar_name": "ليسوتو"},
    {"code": "+267", "en_name": "Botswana", "ar_name": "بوتسوانا"},
    {"code": "+268", "en_name": "Eswatini", "ar_name": "إسواتيني"},
    {"code": "+269", "en_name": "Comoros", "ar_name": "جزر القمر"},
    {"code": "+290", "en_name": "Saint Helena", "ar_name": "سانت هيلينا"},
    {"code": "+291", "en_name": "Eritrea", "ar_name": "إريتريا"},
    {"code": "+297", "en_name": "Aruba", "ar_name": "أروبا"},
    {"code": "+298", "en_name": "Faroe Islands", "ar_name": "جزر فارو"},
    {"code": "+299", "en_name": "Greenland", "ar_name": "جرينلاند"},
    {"code": "+350", "en_name": "Gibraltar", "ar_name": "جبل طارق"},
    {"code": "+351", "en_name": "Portugal", "ar_name": "البرتغال"},
    {"code": "+352", "en_name": "Luxembourg", "ar_name": "لوكسمبورغ"},
    {"code": "+353", "en_name": "Ireland", "ar_name": "أيرلندا"},
    {"code": "+354", "en_name": "Iceland", "ar_name": "أيسلندا"},
    {"code": "+355", "en_name": "Albania", "ar_name": "ألبانيا"},
    {"code": "+356", "en_name": "Malta", "ar_name": "مالطا"},
    {"code": "+357", "en_name": "Cyprus", "ar_name": "قبرص"},
    {"code": "+358", "en_name": "Finland", "ar_name": "فنلندا"},
    {"code": "+359", "en_name": "Bulgaria", "ar_name": "بلغاريا"},
    {"code": "+370", "en_name": "Lithuania", "ar_name": "ليتوانيا"},
    {"code": "+371", "en_name": "Latvia", "ar_name": "لاتفيا"},
    {"code": "+372", "en_name": "Estonia", "ar_name": "استونيا"},
    {"code": "+373", "en_name": "Moldova", "ar_name": "مولدوفا"},
    {"code": "+374", "en_name": "Armenia", "ar_name": "أرمينيا"},
    {"code": "+375", "en_name": "Belarus", "ar_name": "بيلاروسيا"},
    {"code": "+376", "en_name": "Andorra", "ar_name": "أندورا"},
    {"code": "+377", "en_name": "Monaco", "ar_name": "موناكو"},
    {"code": "+378", "en_name": "San Marino", "ar_name": "سان مارينو"},
    {"code": "+379", "en_name": "Vatican City", "ar_name": "مدينة الفاتيكان"},
    {"code": "+380", "en_name": "Ukraine", "ar_name": "أوكرانيا"},
    {"code": "+381", "en_name": "Serbia", "ar_name": "صربيا"},
    {"code": "+382", "en_name": "Montenegro", "ar_name": "الجبل الأسود"},
    {"code": "+383", "en_name": "Kosovo", "ar_name": "كوسوفو"},
    {"code": "+385", "en_name": "Croatia", "ar_name": "كرواتيا"},
    {"code": "+386", "en_name": "Slovenia", "ar_name": "سلوفينيا"},
    {"code": "+387", "en_name": "Bosnia", "ar_name": "البوسنة"},
    {"code": "+389", "en_name": "North Macedonia", "ar_name": "مقدونيا الشمالية"},
    {"code": "+420", "en_name": "Czech Republic", "ar_name": "جمهورية التشيك"},
    {"code": "+421", "en_name": "Slovakia", "ar_name": "سلوفاكيا"},
    {"code": "+423", "en_name": "Liechtenstein", "ar_name": "ليختنشتاين"},
    {"code": "+500", "en_name": "Falkland Islands", "ar_name": "جزر فوكلاند"},
    {"code": "+501", "en_name": "Belize", "ar_name": "بليز"},
    {"code": "+502", "en_name": "Guatemala", "ar_name": "غواتيمالا"},
    {"code": "+503", "en_name": "El Salvador", "ar_name": "السلفادور"},
    {"code": "+504", "en_name": "Honduras", "ar_name": "هندوراس"},
    {"code": "+505", "en_name": "Nicaragua", "ar_name": "نيكاراغوا"},
    {"code": "+506", "en_name": "Costa Rica", "ar_name": "كوستاريكا"},
    {"code": "+507", "en_name": "Panama", "ar_name": "بنما"},
    {"code": "+508", "en_name": "Saint Pierre", "ar_name": "سان بيير"},
    {"code": "+509", "en_name": "Haiti", "ar_name": "هايتي"},
    {"code": "+590", "en_name": "Guadeloupe", "ar_name": "جوادلوب"},
    {"code": "+591", "en_name": "Bolivia", "ar_name": "بوليفيا"},
    {"code": "+592", "en_name": "Guyana", "ar_name": "غيانا"},
    {"code": "+593", "en_name": "Ecuador", "ar_name": "الإكوادور"},
    {"code": "+594", "en_name": "French Guiana", "ar_name": "غويانا الفرنسية"},
    {"code": "+595", "en_name": "Paraguay", "ar_name": "باراغواي"},
    {"code": "+596", "en_name": "Martinique", "ar_name": "مارتينيك"},
    {"code": "+597", "en_name": "Suriname", "ar_name": "سورينام"},
    {"code": "+598", "en_name": "Uruguay", "ar_name": "أوروغواي"},
    {"code": "+670", "en_name": "Timor-Leste", "ar_name": "تيمور الشرقية"},
    {"code": "+673", "en_name": "Brunei", "ar_name": "بروناي"},
    {"code": "+674", "en_name": "Nauru", "ar_name": "ناورو"},
    {"code": "+676", "en_name": "Tonga", "ar_name": "تونغا"},
    {"code": "+677", "en_name": "Solomon Islands", "ar_name": "جزر سليمان"},
    {"code": "+678", "en_name": "Vanuatu", "ar_name": "فانواتو"},
    {"code": "+679", "en_name": "Fiji", "ar_name": "فيجي"},
    {"code": "+680", "en_name": "Palau", "ar_name": "بالاو"},
    {"code": "+682", "en_name": "Cook Islands", "ar_name": "جزر كوك"},
    {"code": "+683", "en_name": "Niue", "ar_name": "نيوي"},
    {"code": "+685", "en_name": "Samoa", "ar_name": "ساموا"},
    {"code": "+686", "en_name": "Kiribati", "ar_name": "كيريباتي"},
    {"code": "+687", "en_name": "New Caledonia", "ar_name": "كاليدونيا الجديدة"},
    {"code": "+688", "en_name": "Tuvalu", "ar_name": "توفالو"},
    {"code": "+689", "en_name": "French Polynesia", "ar_name": "بولينيزيا الفرنسية"},
    {"code": "+690", "en_name": "Tokelau", "ar_name": "توكلاو"},
    {"code": "+691", "en_name": "Micronesia", "ar_name": "ميكرونيزيا"},
    {"code": "+692", "en_name": "Marshall Islands", "ar_name": "جزر مارشال"},
    {"code": "+693", "en_name": "Palau", "ar_name": "بالاو"},
    {"code": "+850", "en_name": "North Korea", "ar_name": "كوريا الشمالية"},
    {"code": "+852", "en_name": "Hong Kong", "ar_name": "هونغ كونغ"},
    {"code": "+853", "en_name": "Macau", "ar_name": "ماكاو"},
    {"code": "+855", "en_name": "Cambodia", "ar_name": "كمبوديا"},
    {"code": "+856", "en_name": "Laos", "ar_name": "لاوس"},
    {"code": "+975", "en_name": "Bhutan", "ar_name": "بوتان"},
    {"code": "+976", "en_name": "Mongolia", "ar_name": "منغوليا"},
    {"code": "+977", "en_name": "Nepal", "ar_name": "نيبال"},
    {"code": "+992", "en_name": "Tajikistan", "ar_name": "طاجيكستان"},
    {"code": "+993", "en_name": "Turkmenistan", "ar_name": "تركمانستان"},
    {"code": "+994", "en_name": "Azerbaijan", "ar_name": "أذربيجان"},
    {"code": "+995", "en_name": "Georgia", "ar_name": "جورجيا"},
    {"code": "+996", "en_name": "Kyrgyzstan", "ar_name": "قرغيزستان"},
    {"code": "+997", "en_name": "Kazakhstan", "ar_name": "كازاخستان"},
    {"code": "+998", "en_name": "Uzbekistan", "ar_name": "أوزبكستان"}
]
